version: '3.8'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${PUBLISH_PORT:-80}:9000"
        healthcheck:
            test: ["CMD", "php", "artisan", "octane:status"]
            interval: 5s
            retries: 8
